/*
 * Program created on 05/19/2024 by:
 * Cristian David Gutiérrez Fernández
 * Diana Laura Sandoval González
 * Arturo Uriel Sosa Ortiz
 * Anthony Alexander Zarate Bautista
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacobrorestaurante;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author diana
 */
public class AgregarMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form AgregarMenu
     */
    String ruta = null;
    CDatos data = new CDatos();
    public AgregarMenu() {
        initComponents();
        setLocationRelativeTo(null);
        
        data.visualizar_tabla(TablaAgreMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNomRes2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAgreMenu = new javax.swing.JTable();
        BtnQuit = new javax.swing.JButton();
        BtnAgre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtFNom = new javax.swing.JTextField();
        TxtFPrec = new javax.swing.JTextField();
        BtnImage = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        lblurl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MInicio = new javax.swing.JMenu();
        SMStart = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Menu");

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        LabelNomRes2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 30)); // NOI18N
        LabelNomRes2.setText("Restaurante Caldo de pollo");

        TablaAgreMenu.setBackground(new java.awt.Color(255, 255, 204));
        TablaAgreMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaAgreMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaAgreMenu);

        BtnQuit.setBackground(new java.awt.Color(255, 255, 51));
        BtnQuit.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        BtnQuit.setText("Quitar");
        BtnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitActionPerformed(evt);
            }
        });

        BtnAgre.setBackground(new java.awt.Color(255, 255, 51));
        BtnAgre.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        BtnAgre.setText("Agregar");
        BtnAgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Imagen:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Precio:");

        TxtFNom.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        TxtFPrec.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        BtnImage.setText("Abrir");
        BtnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImageActionPerformed(evt);
            }
        });

        lblimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblimage.setMaximumSize(new java.awt.Dimension(241, 139));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelNomRes2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtFPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtFNom, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addComponent(BtnImage))
                            .addComponent(lblurl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnQuit)
                            .addComponent(BtnAgre))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LabelNomRes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAgre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BtnImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblurl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TxtFPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtFNom, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MInicio.setText("Inicio");

        SMStart.setText("Inicio");
        SMStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMStartActionPerformed(evt);
            }
        });
        MInicio.add(SMStart);

        jMenuBar1.add(MInicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SMStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMStartActionPerformed
        this.setVisible(false);
        SelecMenu selectMenu = new SelecMenu();
        selectMenu.setVisible(true);
    }//GEN-LAST:event_SMStartActionPerformed

    private void BtnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImageActionPerformed
        JFileChooser j = new JFileChooser();
        int ap = j.showOpenDialog(this);
        
        if (ap == JFileChooser.APPROVE_OPTION) {
            ruta = j.getSelectedFile().getAbsolutePath();
            lblimage.setIcon(new ImageIcon(ruta));
            lblurl.setText(ruta);
        }
    }//GEN-LAST:event_BtnImageActionPerformed

    private void BtnAgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgreActionPerformed
        // Obtiene una instancia de la clase de conexión
        CConexion conex = new CConexion();

        // Obtiene el nombre del producto desde un campo de texto
        String nombre = TxtFNom.getText();

        // Obtiene el precio del producto desde un campo de texto
        String precio = TxtFPrec.getText();

        // Obtiene la URL de la imagen desde una etiqueta
        String url = lblurl.getText();

        // Verifica si los campos no están vacíos
        if (url.trim().isEmpty() || nombre.trim().isEmpty() || precio.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No dejar los campos vacíos");
        } else {
            // Guarda la imagen en la base de datos junto con el nombre y el precio del producto
            try {
                conex.guardar_imagen(url, nombre, precio);
                // Actualiza la tabla que muestra los productos agregados
                data.visualizar_tabla(TablaAgreMenu);
                // Limpia los campos de texto y la etiqueta de la URL y la imagen mostrada
                TxtFNom.setText("");
                TxtFPrec.setText("");
                lblurl.setText("");
                lblimage.setIcon(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar la imagen y los datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnAgreActionPerformed

    private void BtnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitActionPerformed
        // Obtener la fila seleccionada
        int filaSeleccionada = TablaAgreMenu.getSelectedRow();

        if (filaSeleccionada >= 0) {
            try {
                // Obtener el ID de la comida de la fila seleccionada
                int idComida = (int) TablaAgreMenu.getValueAt(filaSeleccionada, 0);

                // Llamar al método DeleteMenu de la clase CDatos
                data.deleteMenu(idComida);

                // Actualizar la tabla después de eliminar los datos
                data.visualizar_tabla(TablaAgreMenu);
            } catch (ClassCastException e) {
                JOptionPane.showMessageDialog(null, "Error al obtener el ID de la comida");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila primero");
        }
    }//GEN-LAST:event_BtnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgre;
    private javax.swing.JButton BtnImage;
    private javax.swing.JButton BtnQuit;
    private javax.swing.JLabel LabelNomRes2;
    private javax.swing.JMenu MInicio;
    private javax.swing.JMenuItem SMStart;
    private javax.swing.JTable TablaAgreMenu;
    private javax.swing.JTextField TxtFNom;
    private javax.swing.JTextField TxtFPrec;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblurl;
    // End of variables declaration//GEN-END:variables
}
