/*
 * Program created on 05/19/2024 by:
 * Cristian David Gutiérrez Fernández
 * Diana Laura Sandoval González
 * Arturo Uriel Sosa Ortiz
 * Anthony Alexander Zarate Bautista
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacobrorestaurante;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author diana
 */
public class GenerarTicket extends javax.swing.JFrame {
    /**
     * Creates new form GenerarTicket
     */
    CDatos datos = new CDatos();
    public GenerarTicket() {
        initComponents();
        setLocationRelativeTo(null);
        TxtFFecha.setEnabled(false);
        
        datos.showTicket(TablaTicket);
        updateDate(); // Actualizar la fecha cuando se inicializa la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        LabelNomRes2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTicket = new javax.swing.JTable();
        BtnEditOrd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtFFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtFHoraFin = new javax.swing.JTextField();
        BtnFinalizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtFHoraInicio = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MInicio3 = new javax.swing.JMenu();
        SMStart = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar Ticket");

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        LabelNomRes2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 30)); // NOI18N
        LabelNomRes2.setText("Restaurante Caldo de pollo");

        TablaTicket.setBackground(new java.awt.Color(255, 255, 204));
        TablaTicket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaTicket);

        BtnEditOrd.setBackground(new java.awt.Color(255, 255, 51));
        BtnEditOrd.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        BtnEditOrd.setText("Editar orden");
        BtnEditOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditOrdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Fecha:");

        TxtFFecha.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Hora inicio:");

        TxtFHoraFin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        BtnFinalizar.setBackground(new java.awt.Color(255, 255, 51));
        BtnFinalizar.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        BtnFinalizar.setText("Finalizar");
        BtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Hora fin:");

        TxtFHoraInicio.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtFHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtFHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnEditOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(LabelNomRes2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                        .addGap(173, 173, 173))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(LabelNomRes2)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtFHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtFHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnEditOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(BtnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        MInicio3.setText("Inicio");

        SMStart.setText("Inicio");
        SMStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMStartActionPerformed(evt);
            }
        });
        MInicio3.add(SMStart);

        jMenuItem2.setText("Refrescar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MInicio3.add(jMenuItem2);

        jMenuBar1.add(MInicio3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void updateDate() {
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String currentDate = dateFormat.format(calendar.getTime());
        TxtFFecha.setText(currentDate);
    }
    
    private void SMStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMStartActionPerformed
        SelecMenu selectMenu = new SelecMenu();
        this.setVisible(false);
        selectMenu.setVisible(true);
    }//GEN-LAST:event_SMStartActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        datos.showTicket(TablaTicket);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void BtnEditOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditOrdActionPerformed
        int selectedRow = TablaTicket.getSelectedRow(); // Obtiene el índice de la fila seleccionada en la tabla
        // Verifica si se ha seleccionado una fila
        if (selectedRow != -1) {
            try {
                // Obtiene el ID del ticket seleccionado de la tabla
                int idTicket = Integer.parseInt(TablaTicket.getValueAt(selectedRow, 0).toString()); // Suponiendo que la columna ID es la primera
                String cantidadStr = JOptionPane.showInputDialog(this, "Ingrese la nueva cantidad:"); // Solicita al usuario ingresar la nueva cantidad mediante un cuadro de diálogo

                // Verifica si se ingresó una cantidad
                if (cantidadStr != null && !cantidadStr.isEmpty()) {
                    int nuevaCantidad = Integer.parseInt(cantidadStr); // Convierte la cantidad ingresada a entero

                    // Verifica que la nueva cantidad sea válida
                    if (nuevaCantidad <= 0) {
                        JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero");
                        return; // Sale del método si la cantidad no es válida
                    }

                    datos.editTicket(idTicket, nuevaCantidad); // Llama al método para editar el ticket con la nueva cantidad
                    datos.showTicket(TablaTicket); // Actualiza la tabla para reflejar los cambios
                }
            } catch (NumberFormatException e) {
                // Maneja el error si la cantidad ingresada no es un número válido
                JOptionPane.showMessageDialog(this, "Cantidad inválida. Por favor, ingrese un número.");
            }
        } else {
            // Muestra un mensaje si no se ha seleccionado ninguna fila en la tabla
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un ticket para editar.");
        }
    }//GEN-LAST:event_BtnEditOrdActionPerformed

    private void BtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizarActionPerformed
        // Obtener la fecha del campo de texto TxtFFecha
        String fecha = TxtFFecha.getText();
        // Obtener la hora de inicio del campo de texto TxtFHoraInicio
        String horaInicio = TxtFHoraInicio.getText();
        // Obtener la hora final del campo de texto TxtFHoraFin
        String horaFinal = TxtFHoraFin.getText();
        // Llamar al método guardarTicket de un objeto llamado datos, pasando como argumentos la hora de inicio y la hora final
        datos.guardarTicket(horaInicio, horaFinal);
        // Limpiar el campo de texto TxtFHoraInicio
        TxtFHoraInicio.setText("");
        // Limpiar el campo de texto TxtFHoraFin
        TxtFHoraFin.setText("");
    }//GEN-LAST:event_BtnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditOrd;
    private javax.swing.JButton BtnFinalizar;
    private javax.swing.JLabel LabelNomRes2;
    private javax.swing.JMenu MInicio3;
    private javax.swing.JMenuItem SMStart;
    private javax.swing.JTable TablaTicket;
    private javax.swing.JTextField TxtFFecha;
    private javax.swing.JTextField TxtFHoraFin;
    private javax.swing.JTextField TxtFHoraInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
