/*
 * Program created on 05/19/2024 by:
 * Cristian David Gutiérrez Fernández
 * Diana Laura Sandoval González
 * Arturo Uriel Sosa Ortiz
 * Anthony Alexander Zarate Bautista
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacobrorestaurante;

import javax.swing.JOptionPane;

/**
 *
 * @author diana
 */
public class SelecMenu extends javax.swing.JFrame {

    /**
     * Creates new form SelecMenu
     */
    CDatos datos = new CDatos();
    public SelecMenu() {
        initComponents();
        setLocationRelativeTo(null);
        
        datos.visualizar_tabla(TablaSelecMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNomRes2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSelecMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TxtFCant = new javax.swing.JTextField();
        BtnAñad = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MInicio2 = new javax.swing.JMenu();
        SMCamNom2 = new javax.swing.JMenuItem();
        MAProd2 = new javax.swing.JMenu();
        SMCom2 = new javax.swing.JMenuItem();
        MTick2 = new javax.swing.JMenu();
        SMVenFin2 = new javax.swing.JMenuItem();
        SMFinOrd2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccionar Menu");

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        LabelNomRes2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 30)); // NOI18N
        LabelNomRes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomRes2.setText("Restaurante Caldo de pollo");

        TablaSelecMenu.setBackground(new java.awt.Color(255, 255, 204));
        TablaSelecMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaSelecMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Imagen", "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaSelecMenu);
        if (TablaSelecMenu.getColumnModel().getColumnCount() > 0) {
            TablaSelecMenu.getColumnModel().getColumn(0).setHeaderValue("Imagen");
            TablaSelecMenu.getColumnModel().getColumn(1).setResizable(false);
            TablaSelecMenu.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            TablaSelecMenu.getColumnModel().getColumn(2).setHeaderValue("Precio");
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad:");

        TxtFCant.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        BtnAñad.setBackground(new java.awt.Color(255, 255, 51));
        BtnAñad.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        BtnAñad.setText("Añadir");
        BtnAñad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(LabelNomRes2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                        .addGap(27, 27, 27)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtFCant, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAñad, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNomRes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAñad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFCant, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(122, 122, 122))
        );

        MInicio2.setText("Inicio");

        SMCamNom2.setText("Refrescar");
        SMCamNom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMCamNom2ActionPerformed(evt);
            }
        });
        MInicio2.add(SMCamNom2);

        jMenuBar1.add(MInicio2);

        MAProd2.setText("Agregar producto");

        SMCom2.setText("Agregar");
        SMCom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMCom2ActionPerformed(evt);
            }
        });
        MAProd2.add(SMCom2);

        jMenuBar1.add(MAProd2);

        MTick2.setText("Ticket");

        SMVenFin2.setText("Ventas finales");
        SMVenFin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMVenFin2ActionPerformed(evt);
            }
        });
        MTick2.add(SMVenFin2);

        SMFinOrd2.setText("Finalizar orden");
        SMFinOrd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMFinOrd2ActionPerformed(evt);
            }
        });
        MTick2.add(SMFinOrd2);

        jMenuBar1.add(MTick2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SMCamNom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMCamNom2ActionPerformed
        datos.visualizar_tabla(TablaSelecMenu);
    }//GEN-LAST:event_SMCamNom2ActionPerformed

    private void SMCom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMCom2ActionPerformed
        AgregarMenu newmenu = new AgregarMenu();
        setVisible(false);
        newmenu.setVisible(true);
    }//GEN-LAST:event_SMCom2ActionPerformed

    private void SMVenFin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMVenFin2ActionPerformed
        HistorialDelDia logday = new HistorialDelDia();
        setVisible(false);
        logday.setVisible(true);
    }//GEN-LAST:event_SMVenFin2ActionPerformed

    private void SMFinOrd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMFinOrd2ActionPerformed
        GenerarTicket ticket = new GenerarTicket();
        setVisible(false);
        ticket.setVisible(true);
    }//GEN-LAST:event_SMFinOrd2ActionPerformed

    private void BtnAñadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadActionPerformed
        // Obtener la fila seleccionada
        int filaSeleccionada = TablaSelecMenu.getSelectedRow();

        if (filaSeleccionada >= 0) {
            try {
                // Obtener el nombre y el precio de la fila seleccionada
                String nombre = TablaSelecMenu.getValueAt(filaSeleccionada, 2).toString();
                double precio = Double.parseDouble(TablaSelecMenu.getValueAt(filaSeleccionada, 3).toString());

                // Obtener la cantidad del campo de texto TxtFCant
                int cantidad = Integer.parseInt(TxtFCant.getText());

                // Verificar que la cantidad sea válida
                if (cantidad <= 0) {
                    JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor que cero");
                    return; // Salir del método si la cantidad no es válida
                }

                // Llamar al método InsertTicket de la clase CDatos
                datos.insertTicket(nombre, precio, cantidad);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad válida");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila primero");
        }
    }//GEN-LAST:event_BtnAñadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñad;
    private javax.swing.JLabel LabelNomRes2;
    private javax.swing.JMenu MAProd2;
    private javax.swing.JMenu MInicio2;
    private javax.swing.JMenu MTick2;
    private javax.swing.JMenuItem SMCamNom2;
    private javax.swing.JMenuItem SMCom2;
    private javax.swing.JMenuItem SMFinOrd2;
    private javax.swing.JMenuItem SMVenFin2;
    private javax.swing.JTable TablaSelecMenu;
    private javax.swing.JTextField TxtFCant;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
